--changeset helen:table_base_card_insert_data
INSERT INTO specification_card (id, card_category, title, in_use, first_question, first_question_category_array, second_question, second_question_category_array)
VALUES
    (300,'BOND','Neighbor', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (301,'BOND','Contact', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (302,'BOND','Enemy', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (303,'BOND','Ally', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (304,'BOND','Beneficiary', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (305,'BOND','Benefactor', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (306,'BOND','Sister', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (307,'BOND','Brother', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (308,'BOND','Friend', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (309,'BOND','Follower', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (310,'BOND','Ancestor', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (311,'BOND','Descendant', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (312,'BOND','Relative', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (313,'BOND','Subordinate', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (314,'BOND','Superior', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (315,'BOND','Stepfather', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (316,'BOND','Stepmother', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (317,'BOND','Economic dependency', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (318,'BOND','Legal relationship', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (319,'BOND','Spiritual advisor', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (320,'BOND','Protector', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (321,'BOND','Convenience relationship', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (322,'BOND','Romantic relationship', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (323,'BOND','Harrier', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (324,'BOND','Muse', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (325,'BOND','Workmate', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (326,'BOND','Rival', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (327,'BOND','Familiar', FALSE, NULL, NULL, NULL, NULL),
    (328,'BOND','Animal companion', FALSE, NULL, NULL, NULL, NULL),
    (329,'BOND','Clockwork golem', FALSE, NULL, NULL, NULL, NULL),
    (330,'BOND','Clockwork familiar', FALSE, NULL, NULL, NULL, NULL),
    (331,'BOND','Mother', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (332,'BOND','Father', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (333,'BOND','Confidant', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (334,'BOND','Slave', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (335,'BOND','Twins', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (336,'BOND','Bastard', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (337,'BOND','Henchman', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (338,'BOND','Chief', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (339,'BOND','Bodyguard', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (340,'BOND','Protégé', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (341,'BOND','Son', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (342,'BOND','Daughter', FALSE, 'Who?', '["PERSONALITY","BACKGROUND"]', NULL, NULL),
    (343,'BOND','Lover', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (344,'BOND','Former lover', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (345,'BOND','Master', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (346,'BOND','Apprentice', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (347,'EVENT','Cosmic event', FALSE, 'Outcome', '["PENTAGRAM"]', NULL, NULL),
    (348,'EVENT','Ritual', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', 'Why?', '["MOON"]'),
    (349,'EVENT','Death', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', 'Why?', '["EVENT"]'),
    (350,'EVENT','Love', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (351,'EVENT','Frenzy', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (352,'EVENT','Seeking redemption', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (353,'EVENT','Humilation', FALSE, 'Why?', '["EVENT"]', 'By who?', '["PERSONALITY","BACKGROUND","BOND"]'),
    (354,'EVENT','Triumph', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (355,'EVENT','Robbery', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', 'Where?', '["PLACE"]'),
    (356,'EVENT','Sabotage', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (357,'EVENT','Rescue mission', FALSE, 'To who?', '["PERSONALITY","BACKGROUND","BOND"]', 'Where?', '["PLACE"]'),
    (358,'EVENT','Suicide mission', FALSE, 'Why?', '["EVENT"]', 'Where?', '["PLACE"]'),
    (359,'EVENT','Rescue', FALSE, 'By who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (360,'EVENT','In trouble', FALSE, 'Why?', '["EVENT"]', 'Where?', '["PLACE"]'),
    (361,'EVENT','Manufacture', FALSE, 'By who?', '["PERSONALITY","BACKGROUND","BOND"]', 'For whom?', '["PERSONALITY","BACKGROUND","BOND"]'),
    (361,'EVENT','Experiment', FALSE, 'Why?', '["MOON"]', 'By who?', '["PERSONALITY","BACKGROUND","BOND"]'),
    (362,'EVENT','Hunt', FALSE, 'To who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (363,'EVENT','Slaughter', FALSE, 'By whom?', '["PERSONALITY","BACKGROUND","BOND"]', 'Where?', '["PLACE"]'),
    (364,'EVENT','New memories', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (365,'EVENT','Oblivion', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (366,'EVENT','Social event', FALSE, 'Starring by', '["PERSONALITY","BACKGROUND","BOND"]', 'Where?', '["PLACE"]'),
    (367,'EVENT','Ball', FALSE, 'Host/ess', '["PERSONALITY","BACKGROUND","BOND"]', 'Where?', '["PLACE"]'),
    (368,'EVENT','Possession', FALSE, 'By who?', '["PENTAGRAM"]', NULL, NULL),
    (369,'EVENT','Revelation', FALSE, 'By who?', '["PENTAGRAM"]', 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]'),
    (370,'EVENT','Revealing the truth', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (371,'EVENT','Research', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (372,'EVENT','Vendetta', FALSE, 'To who?', '["PERSONALITY","BACKGROUND","BOND"]', 'Why?', '["EVENT"]'),
    (373,'EVENT','Sacrifice', FALSE, 'For whom?', '["PERSONALITY","BACKGROUND","BOND"]', 'Why?', '["EVENT"]'),
    (374,'EVENT','Stepping into the darkness', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (375,'EVENT','Following the light', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (376,'EVENT','Eluding fate', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', 'Why?', '["MOON"]'),
    (377,'EVENT','Following destiny', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', 'Why?', '["MOON"]'),
    (378,'EVENT','Logistic operation', FALSE, 'With who?', '["PERSONALITY","BACKGROUND","BOND"]', 'Where?', '["PLACE"]'),
    (379,'EVENT','Regain what was lost', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (380,'EVENT','Cursed', FALSE, 'By who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (381,'EVENT','Blessed', FALSE, 'By who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (382,'EVENT','Wealth', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (383,'EVENT','Bankruptcy', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (384,'EVENT','Pandemic', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (385,'EVENT','End of times', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (386,'EVENT','Selfless sacrifice', FALSE, 'For', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (387,'EVENT','Redemption', FALSE, 'By', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (388,'EVENT','Rivalry', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (389,'EVENT','Friendship', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (390,'EVENT','Rise', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (391,'EVENT','Fall', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (392,'EVENT','Quest', FALSE, 'About', '["PERSONALITY", "BACKGROUND", "BOND", "PLACE"]', NULL, NULL),
    (393,'EVENT','Training', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (394,'EVENT','Duty', FALSE, 'To who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (395,'EVENT','Debt', FALSE, 'To who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (396,'EVENT','Revenge', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', 'Why?', '["EVENT"]'),
    (397,'EVENT','Reward', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', 'Why?', '["EVENT"]'),
    (398,'EVENT','Murder', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', 'Murderer', '["PERSONALITY","BACKGROUND","BOND"]'),
    (399,'EVENT','Hate', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (400,'EVENT','Separation', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (401,'EVENT','Romance', FALSE, 'Who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (402,'EVENT','Secret', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (403,'EVENT','Legend', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (404,'EVENT','Fame', FALSE, 'Why?', '["EVENT"]', 'Where?', '["PLACE"]'),
    (405,'EVENT','Shame', FALSE, 'Why?', '["EVENT"]', 'Where?', '["PLACE"]'),
    (406,'EVENT','Time travel', FALSE, 'Where?', '["PLACE"]', NULL, NULL),
    (407,'EVENT','Corruption', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (408,'EVENT','Sacred mission', FALSE, 'About', '["PERSONALITY","BACKGROUND","BOND","EVENT","PLACE"]', NULL, NULL),
    (409,'EVENT','Destruction', FALSE, 'Why?', '["EVENT"]', 'Where?', '["PLACE"]'),
    (410,'EVENT','Prosthetic limb', FALSE, 'Why?', '["EVENT"]', NULL, NULL),
    (411,'EVENT','Give help', FALSE, 'To who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (412,'EVENT','Be helped', FALSE, 'By whom?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (413,'EVENT','Victory', FALSE, 'To who?', '["PERSONALITY","BACKGROUND","BOND"]',  'Where?', '["PLACE"]'),
    (414,'EVENT','Defeat', FALSE, 'By whom?', '["PERSONALITY","BACKGROUND","BOND"]',  'Where?', '["PLACE"]'),
    (415,'EVENT','Be betrayed', FALSE, 'By whom?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL),
    (416,'EVENT','Betray', FALSE, 'To who?', '["PERSONALITY","BACKGROUND","BOND"]', NULL, NULL);