--changeset helen:table_base_card_insert_data
INSERT INTO base_card (id, card_category, title, in_use)
VALUES
(1,'PERSONALITY','Individualistic', FALSE),
(2,'PENTAGRAM', 'Monster', FALSE),
(3,'PERSONALITY','Cooperative', FALSE),
(4,'MOON', 'Humility', FALSE),
(5,'PERSONALITY','Intuitive', FALSE),
(6,'PENTAGRAM', 'Magical being', FALSE),
(7,'PERSONALITY','Meticulous', FALSE),
(8,'MOON', 'Alienation', FALSE),
(9,'PERSONALITY','Merciful', FALSE),
(10,'PENTAGRAM', 'Wish spell', FALSE),
(11,'PERSONALITY','Cruel', FALSE),
(12,'MOON', 'Disease', FALSE),
(13,'PERSONALITY','Naive', FALSE),
(14,'PENTAGRAM', 'Benevolent spirit', FALSE),
(15,'PERSONALITY','Skeptical', FALSE),
(16,'MOON', 'Amnesia', FALSE),
(17,'PERSONALITY','Shy', FALSE),
(18,'PENTAGRAM', 'Occultist', FALSE),
(19,'PERSONALITY','Seductive', FALSE),
(20,'MOON', 'Lust', FALSE),
(21,'PERSONALITY','Role model', FALSE),
(22,'PENTAGRAM', 'Artificial intelligence', FALSE),
(23,'PERSONALITY','Toxic', FALSE),
(24,'MOON', 'Envy', FALSE),
(25,'PERSONALITY','Trusting', FALSE),
(26,'PENTAGRAM', 'Sage', FALSE),
(27,'PERSONALITY','Distrustful', FALSE),
(28,'MOON', 'Fear', FALSE),
(29,'PERSONALITY','Calculator', FALSE),
(30,'PENTAGRAM', 'Evil creature', FALSE),
(31,'PERSONALITY','Researcher', FALSE),
(32,'MOON', 'Crave for knowledge', FALSE),
(33,'PERSONALITY','Tormented soul', FALSE),
(34,'PENTAGRAM', 'Your imagination', FALSE),
(35,'PERSONALITY','Enthusiastic', FALSE),
(36,'MOON', 'Curiosity', FALSE),
(37,'PERSONALITY','Idealist', FALSE),
(38,'PENTAGRAM', 'Celestial creature', FALSE),
(39,'PERSONALITY','Manipulator', FALSE),
(40,'MOON', 'Psychopathy', FALSE),
(41,'PERSONALITY','Brave', FALSE),
(42,'PENTAGRAM', 'Alien creature', FALSE),
(43,'PERSONALITY','Coward', FALSE),
(44,'MOON', 'Terror', FALSE),
(45,'PERSONALITY','Timorous', FALSE),
(46,'PENTAGRAM', 'Henchman', FALSE),
(47,'PERSONALITY','Resolute', FALSE),
(48,'MOON', 'Hope', FALSE),
(49,'PERSONALITY','Conformist', FALSE),
(50,'PENTAGRAM', 'Lesser demon', FALSE),
(51,'PERSONALITY','Stubborn', FALSE),
(52,'MOON', 'Pride', FALSE),
(53,'PERSONALITY','Competitive', FALSE),
(54,'PENTAGRAM', 'Greater demon', FALSE),
(55,'PERSONALITY','Bohemian', FALSE),
(56,'MOON', 'Sloth', FALSE),
(57,'PERSONALITY','Loyal', FALSE),
(58,'PENTAGRAM', 'Angel', FALSE),
(59,'PERSONALITY','Rebel', FALSE),
(60,'MOON', 'Wrath', FALSE),
(61,'PERSONALITY','Vengeful', FALSE),
(62,'PENTAGRAM', 'Vengeful spirit', FALSE),
(63,'PERSONALITY','Masochistic', FALSE),
(64,'MOON', 'Guilt', FALSE),
(65,'PERSONALITY','Perverted', FALSE),
(66,'PENTAGRAM', 'Evil spirit', FALSE),
(67,'PERSONALITY','Romantic', FALSE),
(68,'MOON', 'Passion', FALSE),
(69,'PERSONALITY','Calm', FALSE),
(70,'PENTAGRAM', 'Great Old Ones', FALSE),
(71,'PERSONALITY','Paranoid', FALSE),
(72,'MOON', 'Insanity', FALSE),
(73,'PERSONALITY','Altruistic', FALSE),
(74,'PENTAGRAM', 'Guardian angel', FALSE),
(75,'PERSONALITY','Ambitious', FALSE),
(76,'MOON', 'Avarice', FALSE),
(77,'PERSONALITY','Sadistic', FALSE),
(78,'PENTAGRAM', 'Fallen Angel', FALSE),
(79,'PERSONALITY','Candid', FALSE),
(80,'MOON', 'Sacrifice', FALSE),
(81,'BACKGROUND', 'Entertainer', FALSE),
(82,'BACKGROUND', 'Artist', FALSE),
(83,'BACKGROUND', 'Journalist', FALSE),
(84,'BACKGROUND', 'Clairvoyant', FALSE),
(85,'BACKGROUND', 'Mindwalker', FALSE),
(86,'BACKGROUND', 'Fallen hero', FALSE),
(87,'BACKGROUND', 'Youthful prodigy', FALSE),
(88,'BACKGROUND', 'Rebellious spirit', FALSE),
(89,'BACKGROUND', 'Non-human', FALSE),
(90,'BACKGROUND', 'Head of criminal organization', FALSE),
(91,'BACKGROUND', 'Scientist', FALSE),
(92,'BACKGROUND', 'Cultist', FALSE),
(93,'BACKGROUND', 'Health worker', FALSE),
(94,'BACKGROUND', 'Lunatic', FALSE),
(95,'BACKGROUND', 'Investigator', FALSE),
(96,'BACKGROUND', 'Law enforcer', FALSE),
(97,'BACKGROUND', 'Criminal', FALSE),
(98,'BACKGROUND', 'Cosmic horror', FALSE),
(99,'BACKGROUND', 'Bartender', FALSE),
(100,'BACKGROUND', 'Prisoner', FALSE),
(101,'BACKGROUND', 'Soldier', FALSE),
(102,'BACKGROUND', 'Student', FALSE),
(103,'BACKGROUND', 'Teacher', FALSE),
(104,'BACKGROUND', 'Dark spirit', FALSE),
(105,'BACKGROUND', 'Fisher', FALSE),
(106,'BACKGROUND', 'Hunter', FALSE),
(107,'BACKGROUND', 'Dealer', FALSE),
(108,'BACKGROUND', 'Smuggler', FALSE),
(109,'BACKGROUND', 'Worker', FALSE),
(110,'BACKGROUND', 'Boss', FALSE),
(111,'BACKGROUND', 'Spy', FALSE),
(112,'BACKGROUND', 'Witness', FALSE),
(113,'BACKGROUND', 'Shadow person', FALSE),
(114,'BACKGROUND', 'Ghost', FALSE),
(115,'BACKGROUND', 'Necromancer', FALSE),
(116,'BACKGROUND', 'Mage', FALSE),
(117,'BACKGROUND', 'Vagabond', FALSE),
(118,'BACKGROUND', 'Merchant', FALSE),
(119,'BACKGROUND', 'Dragon', FALSE),
(120,'BACKGROUND', 'Deity', FALSE),
(121,'BACKGROUND', 'Archeologist', FALSE),
(122,'BACKGROUND', 'Alchemist', FALSE),
(123,'BACKGROUND', 'Assassin', FALSE),
(124,'BACKGROUND', 'Doctor', FALSE),
(125,'BACKGROUND', 'Bastion', FALSE),
(126,'BACKGROUND', 'Inventor', FALSE),
(127,'BACKGROUND', 'Devout', FALSE),
(128,'BACKGROUND', 'Avatar', FALSE),
(129,'BACKGROUND', 'Pirate', FALSE),
(130,'BACKGROUND', 'Sailor', FALSE),
(131,'BACKGROUND', 'Magic item owner', FALSE),
(132,'BACKGROUND', 'Masked guardian', FALSE),
(133,'BACKGROUND', 'Mercenary', FALSE),
(134,'BACKGROUND', 'Vassal', FALSE),
(135,'BACKGROUND', 'Lord', FALSE),
(136,'BACKGROUND', 'Politician', FALSE),
(137,'BACKGROUND', 'Diplomat', FALSE),
(138,'BACKGROUND', 'Forgotten God', FALSE),
(139,'BACKGROUND', 'Celestial being', FALSE),
(140,'BACKGROUND', 'Demon', FALSE),
(141,'BACKGROUND', 'Arbitrator of law', FALSE),
(142,'BACKGROUND', 'Magnate', FALSE),
(143,'BACKGROUND', 'Scrap dealer', FALSE),
(144,'BACKGROUND', 'Mechanic', FALSE),
(145,'BACKGROUND', 'Bandit', FALSE),
(146,'BACKGROUND', 'Monster', FALSE),
(147,'BACKGROUND', 'King', FALSE),
(148,'BACKGROUND', 'Queen', FALSE),
(149,'BACKGROUND', 'Naive hero', FALSE),
(150,'BACKGROUND', 'Anarchist', FALSE),
(151,'BACKGROUND', 'Gambler', FALSE),
(152,'BACKGROUND', 'Gravedigger', FALSE),
(153,'PLACE', 'Factory', FALSE),
(154,'PLACE', 'Laboratory', FALSE),
(155,'PLACE', 'Other dimension', FALSE),
(156,'PLACE', 'Portal between worlds', FALSE),
(157,'PLACE', 'House', FALSE),
(158,'PLACE', 'Sacred place', FALSE),
(159,'PLACE', 'Cursed place', FALSE),
(160,'PLACE', 'Isle', FALSE),
(161,'PLACE', 'Ship', FALSE),
(162,'PLACE', 'Sewers', FALSE),
(163,'PLACE', 'Street', FALSE),
(164,'PLACE', 'Road', FALSE),
(165,'PLACE', 'Temple', FALSE),
(166,'PLACE', 'Sect', FALSE),
(167,'PLACE', 'Vault', FALSE),
(168,'PLACE', 'Millenary tomb', FALSE),
(169,'PLACE', 'Prison', FALSE),
(170,'PLACE', 'Law station', FALSE),
(171,'PLACE', 'Cabin', FALSE),
(172,'PLACE', 'Mansion', FALSE),
(173,'PLACE', 'Airship', FALSE),
(174,'PLACE', 'Hideout', FALSE),
(175,'PLACE', 'Shelter', FALSE),
(176,'PLACE', 'Library', FALSE),
(177,'PLACE', 'Enemy territory', FALSE),
(178,'PLACE', 'Friendly territory', FALSE),
(179,'PLACE', 'Roadside tavern', FALSE),
(180,'PLACE', 'Luxury establishment', FALSE),
(181,'PLACE', 'Secret base', FALSE),
(182,'PLACE', 'Shelter', FALSE),
(183,'PLACE', 'Hospital', FALSE),
(184,'PLACE', 'Asylum', FALSE),
(185,'PLACE', 'Carriage', FALSE),
(186,'PLACE', 'Bank', FALSE),
(187,'PLACE', 'Armory', FALSE),
(188,'PLACE', 'Academy', FALSE),
(189,'PLACE', 'Dungeon', FALSE),
(190,'PLACE', 'Palace', FALSE),
(191,'PLACE', 'Castle', FALSE),
(192,'PLACE', 'Ruins', FALSE),
(193,'PLACE', 'Cave', FALSE),
(194,'PLACE', 'Inn', FALSE),
(195,'PLACE', 'Home', FALSE),
(196,'PLACE', 'Cemetery', FALSE),
(197,'PLACE', 'Temple', FALSE),
(198,'PLACE', 'Glacier', FALSE),
(199,'PLACE', 'Desert', FALSE),
(200,'PLACE', 'Workshop', FALSE),
(201,'PLACE', 'Mountain', FALSE),
(202,'PLACE', 'Forest', FALSE),
(203,'PLACE', 'Island', FALSE),
(204,'PLACE', 'Sea', FALSE),
(205,'PLACE', 'Village', FALSE),
(206,'PLACE', 'City', FALSE),
(207,'PLACE', 'Port', FALSE),
(208,'PLACE', 'Ancestral land', FALSE);
